/*
 * Matryoshka Words
 * By Lewis White
 * This project incorporates knowlage of english language with ability to think creativly.
 */

/**
 *
 * @author lewhi7273
 */
public class NewJFrame extends javax.swing.JFrame {
  String[] wordlist = {"Domino", "Emergency", "Another", "Classroom", "Tornado", "Capital", "Lower", "Flying", "Microphone", "Screenshot", "Plagiarism", "Elementary", "Magazine", "Diamond", "Titanium", "Artichoke", "Avacado", "Hippity", "Hoppitus", "Pneumoia"};
   String A;
   int word;
int toguess = 8;
  
   
  /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rightorwrong = new javax.swing.JLabel();
        wordinput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        iAmright = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        word1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        word2 = new javax.swing.JLabel();
        word3 = new javax.swing.JLabel();
        word4 = new javax.swing.JLabel();
        word5 = new javax.swing.JLabel();
        word6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberofwords = new javax.swing.JLabel();
        word7 = new javax.swing.JLabel();
        word8 = new javax.swing.JLabel();
        giveup = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        chosenword = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numinput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        choosemyword = new javax.swing.JButton();
        lady = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rightorwrong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Guess a word!!");

        iAmright.setText("Am I Right??");
        iAmright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAmrightActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("* Most small words will not work! Be creative!");

        jLabel8.setText("Names will not work either!");

        jLabel9.setText("If a word works but does not show up, I am sorry,");

        jLabel10.setText("I did not have the time to code every single possibility");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("DISCLAIMER:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wordinput, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iAmright, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel6)))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rightorwrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(wordinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iAmright)
                .addGap(18, 18, 18)
                .addComponent(rightorwrong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 310, 329, 307);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Guessed Words!");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Words to Guess...");

        giveup.setText("I give up...");
        giveup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(word2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(word5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(word6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(numberofwords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(word1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(word3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(word4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(word7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addComponent(word8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(giveup, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numberofwords, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(word1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(word2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(word3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(word4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(word5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(word6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(word7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(word8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(giveup)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(350, 0, 200, 614);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        chosenword.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        chosenword.setText("Word-to-be!");
        jPanel3.add(chosenword);
        chosenword.setBounds(60, 70, 130, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Your word is...");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 10, 180, 40);

        numinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numinputActionPerformed(evt);
            }
        });
        jPanel3.add(numinput);
        numinput.setBounds(150, 210, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Pick a number: (0-14)");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 220, 140, 15);

        choosemyword.setText("Choose your word!");
        choosemyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosemywordActionPerformed(evt);
            }
        });
        jPanel3.add(choosemyword);
        choosemyword.setBounds(40, 250, 140, 23);

        lady.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dumbwhitegirl.png"))); // NOI18N
        jPanel3.add(lady);
        lady.setBounds(38, 2, 290, 300);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 330, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numinputActionPerformed

    private void choosemywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosemywordActionPerformed
       double number;
       String chooseword;
      number = Double.parseDouble(numinput.getText());
      
      // Choose number and get word
      chooseword = wordlist[(int)number];
      chosenword.setText(chooseword);
    }//GEN-LAST:event_choosemywordActionPerformed

    private void iAmrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAmrightActionPerformed
       //Get word from text field
        if (word1.getText().equals("") || word2.getText().equals("") || word3.getText().equals("") || word4.getText().equals("") || word5.getText().equals("") || word6.getText().equals("")|| word7.getText().equals("")|| word8.getText().equals("")) {
        A = wordinput.getText();
        
        String baseword = chosenword.getText();
        
        //If certain number is chosen, use these words
        if (baseword.equals("Domino")){       
            wordguessDomino(A);
        }else if (baseword.equals("Emergency")){
            wordguessEmergency(A);
        }else if (baseword.equals("Another")){
            wordguessAnother(A);
        }else if (baseword.equals("Classroom")){
            wordguessClassroom(A);
        }else if (baseword.equals("Tornado")){
            wordguessTornado(A);
        }else if (baseword.equals("Capital")){
            wordguessCapital(A);
        }else if (baseword.equals("Lower")){
            wordguessLower(A);
        }else if (baseword.equals("Flying")){
            wordguessFlying(A);
        }else if (baseword.equals("Microphone")){
            wordguessMicrophone(A);
        }else if (baseword.equals("Screenshot")){
            wordguessScreenshot(A);
        }else if (baseword.equals("Plagarism")){
            wordguessPlagarism(A);  
         }else if (baseword.equals("Upper")){
            wordguessElementary(A);
            }else if (baseword.equals("Magazine")){
            wordguessMagazine(A);
        }else if (baseword.equals("Diamond")){
            wordguessDiamond(A);
        }else if (baseword.equals("Titanium")){
            wordguessTitanium(A);
       
         }
        
        //(WINNING Ending of the game
        if (numberofwords.getText().equals("0")){
            choosemyword.setText("Winner!!");
            chosenword.setText("Winner!!");
            iAmright.setText("Winner!!");
            jLabel11.setText("Winner!!");
            jLabel10.setText("Winner!!");
            rightorwrong.setText("Winner!!");
            jLabel1.setText("Winner!!");
           jLabel2.setText("Winner!!");
           jLabel3.setText("Winner!!");
           jLabel4.setText("Winner!!");
           jLabel5.setText("Winner!!");
           jLabel6.setText("Winner!!");
           jLabel7.setText("Winner!!");
           jLabel8.setText("Winner!!");
           jLabel9.setText("Winner!!");
           numberofwords.setText("Winner!!");
      
           
        }
        }
    }//GEN-LAST:event_iAmrightActionPerformed

    private void giveupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveupActionPerformed
      //LOSER Ending of the game
        
            choosemyword.setText("Loser!!");
            chosenword.setText("Loser!!");
            iAmright.setText("Loser!!");
            jLabel11.setText("Loser!!");
            jLabel10.setText("Loser!!");
            rightorwrong.setText("Loser!!");
            jLabel1.setText("Loser!!");
           jLabel2.setText("Loser!!");
           jLabel3.setText("Loser!!");
           jLabel4.setText("Loser!!");
           jLabel5.setText("Loser!!");
           jLabel6.setText("Loser!!");
           jLabel7.setText("Loser!!");
           jLabel8.setText("Loser!!");
           jLabel9.setText("Loser!!");
           numberofwords.setText("Loser!!");
    
    }//GEN-LAST:event_giveupActionPerformed
/**
 * 
 * Word is chosen based on number picked
 * Displays the word, and allows user to enter guesses
 * 
 * 
 */                
    public void wordguessDomino(String A){
    //while (word1.getText().equals("") || word2.getText().equals("") || word3.getText().equals("") || word4.getText().equals("") || word5.getText().equals("") || word6.getText().equals("")) {
         
    if (A.equalsIgnoreCase("Do")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
           wordinput.setText("");
            
        } else if (A.equalsIgnoreCase("Doom")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("Ion")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("Mood")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("Moon")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("Mind")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("Mino")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("Nod")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
        
        
        
        
         
    //}
    
    
    
}

public void wordguessEmergency(String A){
    
         
    if (A.equalsIgnoreCase("energy")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("enemy")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("greece")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("green")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("emerge")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("gym")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("eye")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("merge")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
  
     
   
      }
    /**
     * @param args the command line arguments
     */
            
}    

public void wordguessAnother(String A){
    
    
    if (A.equalsIgnoreCase("throne")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("hornet")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("heart")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("then")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("other")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("earth")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("north")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("heat")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
             
}
        }

public void wordguessClassroom(String A){
    
    if (A.equalsIgnoreCase("class")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("room")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("across")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("solar")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("cool")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("molar")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("mass")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("coral")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}

public void wordguessTornado(String A){
   
    if (A.equalsIgnoreCase("road")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("odor")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("torn")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("onto")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("rant")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("dart")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("donator")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("toad")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}

public void wordguessCapital(String A){
    
    if (A.equalsIgnoreCase("clap")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("pal")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("lip")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("lit")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("cap")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("tip")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("pit")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("tap")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}

public void wordguessLower(String A){
    if (A.equalsIgnoreCase("wore")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("role")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("low")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("lore")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("owl")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("lore")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("we")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("row")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}

public void wordguessFlying(String A){
    if (A.equalsIgnoreCase("fling")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("lying")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("fly")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("if")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("gin")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("gif")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("in")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("fin")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}

public void wordguessMicrophone(String A){
    if (A.equalsIgnoreCase("morphine")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("phone")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("micro")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("income")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("prince")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("chrome")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("home")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("poor")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}

public void wordguessScreenshot(String A){
    if (A.equalsIgnoreCase("screen")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("shot")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("horse")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("other")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("seen")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("enter")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("chess")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("chest")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}

public void wordguessPlagarism(String A){
    if (A.equalsIgnoreCase("grandpa")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("plasma")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("alarm")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("palm")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("salami")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("lima")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("grail")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("ramp")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}

public void wordguessElementary(String A){
    if (A.equalsIgnoreCase("rename")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("antler")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("neat")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("eatery")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("enter")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("element")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("ramen")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("name")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}

public void wordguessMagazine(String A){
     if (A.equalsIgnoreCase("amazing")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("anime")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("amaze")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("manage")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("image")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("game")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("mega")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("main")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}

public void wordguessDiamond(String A){
        if (A.equalsIgnoreCase("domain")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("mind")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("odd")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("main")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("admin")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("dad")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("damn")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("ion")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
   }
   
public void wordguessTitanium(String A){
     if (A.equalsIgnoreCase("mutant")){
            word1.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
           
            //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
             wordinput.setText("");
        } else if (A.equalsIgnoreCase("multi")) {
           word2.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("titan")){
            word3.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("tuna")){
            word4.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("main")){
            word5.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else if (A.equalsIgnoreCase("taunt")){
            word6.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }  else if (A.equalsIgnoreCase("mini")) {
           word7.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        }else if (A.equalsIgnoreCase("aunt")) {
           word8.setText(A);
            rightorwrong.setText("Great job, keep guessing!");
            
              //change number of remaining words
             toguess--;
           numberofwords.setText("" + toguess);
            wordinput.setText("");
        } else {
            rightorwrong.setText("Try again!");
             wordinput.setText("");
        }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choosemyword;
    private javax.swing.JLabel chosenword;
    private javax.swing.JButton giveup;
    private javax.swing.JButton iAmright;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lady;
    private javax.swing.JLabel numberofwords;
    private javax.swing.JTextField numinput;
    private javax.swing.JLabel rightorwrong;
    private javax.swing.JLabel word1;
    private javax.swing.JLabel word2;
    private javax.swing.JLabel word3;
    private javax.swing.JLabel word4;
    private javax.swing.JLabel word5;
    private javax.swing.JLabel word6;
    private javax.swing.JLabel word7;
    private javax.swing.JLabel word8;
    private javax.swing.JTextField wordinput;
    // End of variables declaration//GEN-END:variables
}
